spring.application.name=Life4Change

server.port=2506

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://mysqldb:3306/life4changedb
#spring.datasource.url=jdbc:mysql://localhost:3306/life4change
spring.datasource.url=jdbc:mysql://database-1.c43ym48q0r2w.us-east-1.rds.amazonaws.com/life4change?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=adminaws

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/bloodbankapi/swagger
